<?php

namespace App\CourseBundle\Repository;

/**
 * ChooseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChooseRepository extends \Doctrine\ORM\EntityRepository
{
}
