<?php

namespace App\CourseBundle\Repository;

use App\CourseBundle\Entity\Pattern;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * PatternRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatternRepository extends \Doctrine\ORM\EntityRepository
{

  /**
   * @param array   $nodes Request data
   */
  public function save($data, $question) {
      $query = new Pattern();
      $query->setQuestion($question);
      $query->setAnswer($data["answer"]);

      $this->_em->persist($query);
      $this->_em->flush();
  }

}
