<?php

namespace App\CourseBundle\Repository;

/**
 * SoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoundRepository extends \Doctrine\ORM\EntityRepository
{
}
