<?php

namespace App\CourseBundle\Repository;

use App\CourseBundle\Entity\UserCourse;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * UserCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCourseRepository extends \Doctrine\ORM\EntityRepository
{
 /**
   * @param array   $nodes Request data
   */
  public function save($user, $id) {
      $query = new UserCourse();
      $query->setUser($user);
      $query->setCourse($id);

      $this->_em->persist($query);
      $this->_em->flush();
  }

    /**
  * @return \Doctrine\ORM\Query
  */
  public function findByUserCourse($user, $course) {
    $query = $this->findByUserCourseQb($user, $course);

    return $query->getQuery();
  }

  /**
  * Return QueryBuilder for question by id
  *
  * @return \Doctrine\ORM\QueryBuilder
  */
  public function findByUserCourseQb($user, $course) {
    if ($user == null && $course == null) {
      throw new BadRequestHttpException("No id's provided");
    }

    $query = $this->findSimple('usercourse')
      ->andWhere('usercourse.user = :user')
      ->andWhere('usercourse.course = :course')
      ->setParameters(array(':user' => $user, ':course' => $course));
      
    return $query;
  }

  /**
  * @return \Doctrine\ORM\QueryBuilder
  */
  private function findSimple($fields = null) {
    $query = $this->createQueryBuilder('usercourse')
      ->select($fields);

    return $query;
  }

}
