app_user:
  resource: "@AppUsersBundle/Resources/config/routing.yml"
  prefix:   /

app_course:
  resource: "@AppCourseBundle/Resources/config/routing.yml"
  prefix:   /

app_dashboard:
  resource: "@AppDashboardBundle/Resources/config/routing.yml"
  prefix:   /

#Vendor
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

