fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_course:
    resource: "@AppCourseBundle/Resources/config/routing.yml"
    prefix:   /

app_dashboard:
    resource: "@AppDashboardBundle/Resources/config/routing.yml"
    prefix:   /

