App\CourseBundle\Entity\Choose:
  type: entity
  table: choose
  repositoryClass: App\CourseBundle\Repository\ChooseRepository

  manyToOne:
    question:
      targetEntity: App\CourseBundle\Entity\Question
      inversedBy: chooses
      joinColumn:
        name: question_id
        referencedColumnName: id

  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  lifecycleCallbacks: {  }