App\CourseBundle\Entity\Course:
  type: entity
  table: course
  repositoryClass: App\CourseBundle\Repository\CourseRepository
  
  oneToMany:
    questions:
      targetEntity: App\CourseBundle\Entity\Question
      mappedBy: course
    usercourses:
      targetEntity: App\CourseBundle\Entity\UserCourse
      mappedBy: course

  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
  lifecycleCallbacks: {  }
