App\CourseBundle\Entity\Image:
  type: entity
  table: image
  repositoryClass: App\CourseBundle\Repository\ImageRepository

  manyToOne:
    question:
      targetEntity: App\CourseBundle\Entity\Question
      inversedBy: images
      joinColumn:
        name: question_id
        referencedColumnName: id
      
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO    
  fields:
    base64:
      type: string 
      length: 20000
  lifecycleCallbacks: {  }
