App\CourseBundle\Entity\Question:
  type: entity
  table: question
  repositoryClass: App\CourseBundle\Repository\QuestionRepository
  
  manyToOne:
    course:
      targetEntity: App\CourseBundle\Entity\Course
      inversedBy: questions
      joinColumn:
        name: course_id
        referencedColumnName: id
  oneToMany:
    chooses:
      targetEntity: App\CourseBundle\Entity\Choose
      mappedBy: question
    sounds:
      targetEntity: App\CourseBundle\Entity\Sound
      mappedBy: question
    images:
      targetEntity: App\CourseBundle\Entity\Image
      mappedBy: question

  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    type:
      type: integer
    sound:
      type: boolean
    image:
      type: boolean
    choose:
      type: boolean
    title:
      type: string
      length: 255
    answer:
      type: string
      length: 255
    question:
      type: string
      length: 255
    difficulty:
      type: integer
  lifecycleCallbacks: {  }
