App\CourseBundle\Entity\Score:
  type: entity
  table: score
  repositoryClass: App\CourseBundle\Repository\ScoreRepository

  manyToOne:
    user:
      targetEntity: App\UsersBundle\Entity\User
      inversedBy: score
      joinColumn:
        name: user_id
        referencedColumnName: id

  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    text:
      text: integer
    sound:
      sound: integer
    choose:
      choose: integer
    image:
      image: integer
    stt:
      stt: integer
    stc:
      stc: integer
    tt:
      tt: integer
    tc:
      tc: integer
    st:
      st: integer
    sc:
      sc: integer
    it:
      it: integer
    ic:
      ic: integer
    ist:
      ist: integer
    isc:
      isc: integer
    total:
      total: integer
  lifecycleCallbacks: {  }