course:
    path:     /course
    defaults: { _controller: AppCourseBundle:Course:course }
question:
    path:     /question/{id}
    defaults: { _controller: AppCourseBundle:Course:question }
    options:
        expose: true
answer:
    path:     /answer
    defaults: { _controller: AppCourseBundle:Course:answer }
    options:
        expose: true
create:
    path:     /create
    defaults: { _controller: AppCourseBundle:Course:create }
    options:
        expose: true

