parameters:
  #Repositories classes
  course.repository.class: 'App\CourseBundle\Repository\CourseRepository'
  question.repository.class: 'App\CourseBundle\Repository\QuestionRepository'
  choose.repository.class: 'App\CourseBundle\Repository\ChooseRepository'
  score.repository.class: 'App\CourseBundle\Repository\ScoreRepository'
  pattern.repository.class: 'App\CourseBundle\Repository\PatternRepository'
  image.repository.class: 'App\CourseBundle\Repository\ImageRepository'
  usercourse.repository.class: 'App\CourseBundle\Repository\UserCourseRepository'
  #Repositories entity
  course.repository.entity: 'App\CourseBundle\Entity\Course'
  question.repository.entity: 'App\CourseBundle\Entity\Question'
  choose.repository.entity: 'App\CourseBundle\Entity\Choose'
  score.repository.entity: 'App\CourseBundle\Entity\Score'
  pattern.repository.entity: 'App\CourseBundle\Entity\Pattern'
  image.repository.entity: 'App\CourseBundle\Entity\Image'
  usercourse.repository.entity: 'App\CourseBundle\Entity\UserCourse'
  #Services classes
  course.service.class: 'App\CourseBundle\Services\CourseService'
  question.service.class: 'App\CourseBundle\Services\QuestionService'
  choose.service.class: 'App\CourseBundle\Services\ChooseService'
  score.service.class: 'App\CourseBundle\Services\ScoreService'
  pattern.service.class: 'App\CourseBundle\Services\PatternService'
  image.service.class: 'App\CourseBundle\Services\ImageService'
  usercourse.service.class: 'App\CourseBundle\Services\UserCourseService'
  #Forms classes
  question.form.class: 'App\CourseBundle\Form\Type\questionType'  
services:
  #Repositories
  course.repository:
    class: '%course.repository.class%'
    public: false
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['%course.repository.entity%']
  question.repository:
    class: '%question.repository.class%'
    public: false
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['%question.repository.entity%']
  choose.repository:
    class: '%choose.repository.class%'
    public: false
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['%choose.repository.entity%']
  score.repository:
    class: '%score.repository.class%'
    public: false
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['%score.repository.entity%']
  pattern.repository:
    class: '%pattern.repository.class%'
    public: false
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['%pattern.repository.entity%']
  image.repository:
    class: '%image.repository.class%'
    public: false
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['%image.repository.entity%']
  usercourse.repository:
    class: '%usercourse.repository.class%'
    public: false
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['%usercourse.repository.entity%']
  #Services
  course.service:
    class: '%course.service.class%'
    arguments: ['@course.repository']
    scope: request
  question.service:
    class: '%question.service.class%'
    arguments: ['@question.repository']
    scope: request
  choose.service:
    class: '%choose.service.class%'
    arguments: ['@choose.repository']
    scope: request
  score.service:
    class: '%score.service.class%'
    arguments: ['@score.repository']
    scope: request
  pattern.service:
    class: '%pattern.service.class%'
    arguments: ['@pattern.repository']
    scope: request
  image.service:
    class: '%image.service.class%'
    arguments: ['@image.repository']
    scope: request
  usercourse.service:
    class: '%usercourse.service.class%'
    arguments: ['@usercourse.repository']
    scope: request
  #Forms
  question.form:
    class: '%question.form.class%'
    tags:
      - { name: form.type, alias: app_erp_question }
